language: node_js
sudo: required
dist: trusty
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "node"
  - "6"
install:
  - npm install
  - bower install
  - npm install -g polymer-cli
  - polymer install
before_script:
  - npm run lint
script:
  - polymer build --verbose --preset es5-bundled
