language: node_js
sudo: required
dist: trusty
node_js:
  - "node"
  - "6"
install:
  - npm install
  - npm install -g polymer-cli bower
  - bower install
  - polymer install
before_script:
  - npm run lint
script:
  - polymer build --verbose --preset es5-bundled
